# Generated by Django 3.1.7 on 2021-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Uploaded/userprofile', verbose_name='profile picture'),
        ),
    ]
