# Generated by Django 3.1.7 on 2021-05-21 14:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hichhike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_type', models.CharField(choices=[('d', 'راننده'), ('p', 'مسافر')], max_length=1)),
                ('creator_gender', models.CharField(choices=[('m', 'اقا'), ('f', 'خانوم')], max_length=1)),
                ('creator_age', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('fellow_traveler_num', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('cities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trip_time', models.DateTimeField(blank=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_hichhike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
