# Generated by Django 3.1.13 on 2021-07-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hichhike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants_passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='hichhike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JoinRequest_hichhike', to='hichhike.hichhike'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JoinRequest_passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hichhike',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_hichhike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('hichhike', 'passenger')},
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('hichhike', 'passenger')},
        ),
    ]
