# Generated by Django 3.1.7 on 2021-05-18 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hichhike', '0002_hichhike_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hichhike',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='hichhike',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hichhike',
            name='trip_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
