# Generated by Django 3.1.7 on 2021-06-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hichhike', '0003_auto_20210521_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hichhike',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hichhike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants_hichhike', to='hichhike.hichhike')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants_passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hichhike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JoinRequest_hichhike', to='hichhike.hichhike')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JoinRequest_passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
