# Generated by Django 3.1.7 on 2021-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hichhike', '0004_auto_20210605_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
