# Generated by Django 3.1.7 on 2021-06-05 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hichhike', '0005_joinrequest_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('hichhike', 'passenger')},
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('hichhike', 'passenger')},
        ),
    ]
