version: '3.7'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    #command: sh -c "python manage.py migrate && gunicorn ScoutingLegion.wsgi -b 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/scoutinglegion
    depends_on:
      - db_sl
    ports:
      - "8000:8000"
 #   networks:
 #     - main
    restart: on-failure
  db_sl:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_sl
      - POSTGRES_PORT=5432
    #networks:
    #  - main
    ports:
      - "5432:5432"
    restart: on-failure
  #nginx:
  #  container_name: nginx
  #  command: nginx -g 'daemon off;'
  #  depends_on:
  #    - web
  #  image: nginx:latest
  #  networks:
  #    - main
  #  ports:
  #    - "80:80"
  #  restart: on-failure
  #  volumes:
  #  - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  postgres_data:
#networks:
#  main:
