# FROM postgres
# COPY ./install-extensions.sql /docker-entrypoint-initdb.d
# ENV POSTGRES_DB 'db_sl'
# ENV POSTGRES_USER 'postgres'
# ENV POSTGRES_PASSWORD '1234'
# ENV POSTGRES_PORT '5432'

# COPY .load-extensions.sql /docker-entrypoint-initdb.d/
# RUN CREATE EXTENSION pg_trgm;