# Generated by Django 3.1.7 on 2021-05-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=200, verbose_name='name')),
                ('latitude', models.FloatField(verbose_name='location latitude')),
                ('longitude', models.FloatField(verbose_name='location longitude')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='type')),
                ('city', models.CharField(max_length=100, verbose_name='city of location')),
                ('state', models.CharField(max_length=100, verbose_name='state of location')),
                ('loc_picture', models.ImageField(blank=True, null=True, upload_to='Uploaded/location_picture', verbose_name='location picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='location description')),
                ('address', models.CharField(max_length=200, verbose_name='location address')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
