# Generated by Django 3.1.7 on 2021-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
    ]
