# Generated by Django 3.1.7 on 2021-04-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_auto_20210418_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='loc_name',
        ),
    ]
