# Generated by Django 3.1.7 on 2021-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_remove_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default=None, max_length=200, verbose_name='location address'),
        ),
    ]
