# Generated by Django 3.1.7 on 2021-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_auto_20210502_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, verbose_name='location address'),
        ),
    ]
