# Generated by Django 3.1.7 on 2021-05-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0004_auto_20210502_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='kinds',
            field=models.ManyToManyField(related_name='location', to='Locations.Category'),
        ),
    ]
