# Generated by Django 3.1.13 on 2021-07-07 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lrate', to='Locations.location')),
                ('user_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Urate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_rate', 'location')},
            },
        ),
    ]
