# Generated by Django 3.1.7 on 2021-04-28 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0004_auto_20210428_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ManyToManyField(related_name='creator_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
