# Generated by Django 3.1.13 on 2021-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0005_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
