# Generated by Django 3.1.7 on 2021-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0005_auto_20210504_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is private location'),
        ),
    ]
