# Generated by Django 3.1.7 on 2021-05-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0006_auto_20210507_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
    ]
