# Generated by Django 3.1.7 on 2021-05-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0007_remove_location_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_picture',
            new_name='image',
        ),
    ]
