# Generated by Django 3.1.7 on 2021-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0008_auto_20210517_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='loc_name',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='name'),
        ),
    ]
